### ISSUE TITLE
peing.net以外の質問箱をどうするか

### ISSUE THREAD

**Issue by bluesura** [vytfs/wiki#15]
追加案：
キャラクターのデータにsarahah、marshmallow

事例:
雨下カイト https://twitter.com/AmashitaKite/status/953969544313229312
織神ゆさ https://twitter.com/origamiyusa

**Comment by tamaina** [comment]
frontmatterは別に何を追加してもよくて(つまり現状でもデータの追加は自由)、あとはテンプレートテーブルの表記部分を追加するだけなんですが、ちょっと一個ずつ処理していくのが面倒臭くなってきたのでjsonファイルで定義してfor(...in...)でお手軽にサービスを追加できるようにしたいですね
